### ISSUE TITLE
Can't get the extension to work

### ISSUE THREAD

**Issue by darthnorman** [krausandre/wsm-form-spamshield#8] opened 2023-11-28 14:20 UTC
I tried to add the validator to my form but the form tells me I am a robot. What is wrong with my setup?

TYPO3 v11 LTS
wsm_form_spamshield 1.3.2

I did flush TYPO3 and PHP caches after install.

I am using my own Form setup that inherits from "TYPO3.CMS.Form.prototypes.standard".

The field is there, the Javascript does its thing and writes all values into the value of the input.

I use securityLevel: 1 and formTimeout: 5 but still no success.

**Comment by darthnorman** [comment] 2023-11-28 15:38
SecurityCheckValidator.php seems to stop at line 63, because $securityChecks is always empty, the json_decode always returns NULL. But I can't figure out why, ValidationResultProvider::getValidationResult() looks to be a valid json string.

**Comment by darthnorman** [comment] 2023-11-28 16:36
Adding `html_entity_decode() ` solves the problem for me.

Line 50: `$securityChecks = json_decode(html_entity_decode(ValidationResultProvider::getValidationResult()), true);`

**Comment by darthnorman** [comment] 2023-11-29 09:08
It looks like [mksanitizedparameters](https://github.com/DMKEBUSINESSGMBH/typo3-mksanitizedparameters) is causing this behaviour, by sanitizing the JSON that is sent by the form.

**Comment by krausandre** [comment] 2023-12-01 18:33
Hi @darthnorman, thank you for the report. Currently I couldn't reproduce it. Can you tell me a little more about your environment?
Which TYPO3 Version exactly?
Is the server Apache or nginx?
Which PHP Version do you use?
What extensions do you have installed in your setup?
Do you have any other special fields or maybe form related configuration like a captcha or something else?
Maybe, if possible, can you give me your form.yaml code? (anonymized, no critical data, you can send it per dm maybe on slack Andre Kraus)

**Comment by darthnorman** [comment] 2024-02-29 12:49
Hi, it wasn't your fault, it was ours. The extension I mentioned in my last comment prevented submitting the form.

Issue can be closed, thank you.

**Comment by krausandre** [comment] 2024-03-02 10:39
Hi Norman,
thank you for clearifying this.
I close this issue.

**Closed as completed by krausandre** 2024-03-02 10:39 UTC
